# Generated by Django 5.2.8 on 2025-11-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracking', '0003_blockedip'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('reason', models.TextField()),
                ('flagged_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
